-- Healthcare Data Integration: Database & Schema Setup
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_INTEGRATION;
USE DATABASE HEALTHCARE_INTEGRATION;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS AI;
CREATE SCHEMA IF NOT EXISTS ML;
CREATE SCHEMA IF NOT EXISTS SEARCH;
CREATE SCHEMA IF NOT EXISTS APP;

USE WAREHOUSE CORTEX;
