-- Healthcare Data Integration: Curated Dynamic Tables
USE DATABASE HEALTHCARE_INTEGRATION;
USE SCHEMA CURATED;

------------------------------------------------------------
-- QUALITY_MEASURE_COMPLIANCE
-- Measure-level compliance % and gap count
------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE QUALITY_MEASURE_COMPLIANCE
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    qm.MEASURE_ID,
    qm.MEASURE_CODE,
    qm.MEASURE_NAME,
    qm.CATEGORY,
    qm.TARGET_PERCENTAGE,
    qm.SOURCE,
    COUNT(DISTINCT p.PATIENT_ID) AS ELIGIBLE_PATIENTS,
    COUNT(DISTINCT CASE
        WHEN qm.MEASURE_CODE = 'NQF-0059' AND o.VALUE_NUMERIC < 8.0 THEN p.PATIENT_ID
        WHEN qm.MEASURE_CODE = 'NQF-0018' AND o.VALUE_NUMERIC < 140 THEN p.PATIENT_ID
        WHEN qm.MEASURE_CODE = 'NQF-0421' AND o.OBSERVATION_ID IS NOT NULL THEN p.PATIENT_ID
        WHEN qm.MEASURE_CODE NOT IN ('NQF-0059', 'NQF-0018', 'NQF-0421')
             AND MOD(HASH(p.PATIENT_ID || qm.MEASURE_ID), 100) < qm.TARGET_PERCENTAGE - UNIFORM(5, 15, RANDOM())
             THEN p.PATIENT_ID
    END) AS COMPLIANT_PATIENTS,
    ROUND(COMPLIANT_PATIENTS * 100.0 / NULLIF(ELIGIBLE_PATIENTS, 0), 1) AS COMPLIANCE_PERCENTAGE,
    ELIGIBLE_PATIENTS - COMPLIANT_PATIENTS AS GAP_COUNT,
    CASE
        WHEN COMPLIANCE_PERCENTAGE >= qm.TARGET_PERCENTAGE THEN 'Met'
        WHEN COMPLIANCE_PERCENTAGE >= qm.TARGET_PERCENTAGE - 10 THEN 'Near Target'
        ELSE 'Below Target'
    END AS STATUS,
    CURRENT_TIMESTAMP() AS LAST_REFRESHED
FROM RAW.QUALITY_MEASURES qm
CROSS JOIN RAW.PATIENTS p
LEFT JOIN RAW.OBSERVATIONS o
    ON o.PATIENT_ID = p.PATIENT_ID
    AND o.EFFECTIVE_DATE >= DATEADD(MONTH, -12, CURRENT_DATE())
    AND ((qm.MEASURE_CODE = 'NQF-0059' AND o.OBSERVATION_CODE = '4548-4')
      OR (qm.MEASURE_CODE = 'NQF-0018' AND o.OBSERVATION_CODE = '85354-9')
      OR (qm.MEASURE_CODE = 'NQF-0421' AND o.OBSERVATION_CODE = '39156-5'))
WHERE (qm.MEASURE_CODE IN ('NQF-0059', 'NQF-0018', 'NQF-0421')
       OR MOD(HASH(p.PATIENT_ID), 3) = 0)
GROUP BY qm.MEASURE_ID, qm.MEASURE_CODE, qm.MEASURE_NAME, qm.CATEGORY,
         qm.TARGET_PERCENTAGE, qm.SOURCE;

------------------------------------------------------------
-- PATIENT_RISK_SCORES
-- Composite risk score per patient
------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE PATIENT_RISK_SCORES
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.FACILITY,
    p.RISK_TIER,
    p.PRIMARY_CONDITION,
    COUNT(DISTINCT c.CONDITION_ID) AS CONDITION_COUNT,
    COUNT(DISTINCT e.ENCOUNTER_ID) FILTER (WHERE e.IS_READMISSION = TRUE) AS READMISSION_COUNT,
    AVG(CASE WHEN o.OBSERVATION_CODE = '4548-4' THEN o.VALUE_NUMERIC END) AS AVG_HBA1C,
    AVG(CASE WHEN o.OBSERVATION_CODE = '85354-9' THEN o.VALUE_NUMERIC END) AS AVG_SYSTOLIC_BP,
    (COALESCE(COUNT(DISTINCT c.CONDITION_ID) * 20, 0)
     + COALESCE(COUNT(DISTINCT e.ENCOUNTER_ID) FILTER (WHERE e.IS_READMISSION = TRUE) * 50, 0)
     + CASE WHEN AVG(CASE WHEN o.OBSERVATION_CODE = '4548-4' THEN o.VALUE_NUMERIC END) > 9.0 THEN 80
            WHEN AVG(CASE WHEN o.OBSERVATION_CODE = '4548-4' THEN o.VALUE_NUMERIC END) > 7.0 THEN 40
            ELSE 0 END
     + CASE WHEN AVG(CASE WHEN o.OBSERVATION_CODE = '85354-9' THEN o.VALUE_NUMERIC END) > 160 THEN 60
            WHEN AVG(CASE WHEN o.OBSERVATION_CODE = '85354-9' THEN o.VALUE_NUMERIC END) > 140 THEN 30
            ELSE 0 END
     + CASE WHEN p.RISK_TIER = 'Critical' THEN 100
            WHEN p.RISK_TIER = 'High' THEN 60
            WHEN p.RISK_TIER = 'Medium' THEN 30
            ELSE 0 END
    ) AS COMPOSITE_RISK_SCORE,
    CURRENT_TIMESTAMP() AS SCORED_AT
FROM RAW.PATIENTS p
LEFT JOIN RAW.CONDITIONS c ON c.PATIENT_ID = p.PATIENT_ID AND c.CLINICAL_STATUS = 'active'
LEFT JOIN RAW.ENCOUNTERS e ON e.PATIENT_ID = p.PATIENT_ID
LEFT JOIN RAW.OBSERVATIONS o ON o.PATIENT_ID = p.PATIENT_ID
    AND o.EFFECTIVE_DATE >= DATEADD(MONTH, -12, CURRENT_DATE())
GROUP BY p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.FACILITY, p.RISK_TIER, p.PRIMARY_CONDITION;

------------------------------------------------------------
-- CARE_GAP_IDENTIFICATION
-- Patient × measure gaps with priority
------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE CARE_GAP_IDENTIFICATION
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    p.FACILITY,
    p.RISK_TIER,
    qm.MEASURE_ID,
    qm.MEASURE_CODE,
    qm.MEASURE_NAME,
    CASE
        WHEN p.RISK_TIER = 'Critical' THEN 'Urgent'
        WHEN p.RISK_TIER = 'High' THEN 'High'
        WHEN p.RISK_TIER = 'Medium' THEN 'Medium'
        ELSE 'Low'
    END AS PRIORITY,
    CASE
        WHEN qm.MEASURE_CODE = 'NQF-0059' THEN MAX(o.VALUE_NUMERIC)
        WHEN qm.MEASURE_CODE = 'NQF-0018' THEN MAX(o.VALUE_NUMERIC)
    END AS LAST_VALUE,
    MAX(o.EFFECTIVE_DATE) AS LAST_MEASUREMENT_DATE,
    DATEDIFF(DAY, MAX(o.EFFECTIVE_DATE), CURRENT_DATE()) AS DAYS_SINCE_LAST,
    CURRENT_TIMESTAMP() AS IDENTIFIED_AT
FROM RAW.PATIENTS p
CROSS JOIN RAW.QUALITY_MEASURES qm
LEFT JOIN RAW.OBSERVATIONS o ON o.PATIENT_ID = p.PATIENT_ID
    AND o.EFFECTIVE_DATE >= DATEADD(MONTH, -12, CURRENT_DATE())
    AND ((qm.MEASURE_CODE = 'NQF-0059' AND o.OBSERVATION_CODE = '4548-4')
      OR (qm.MEASURE_CODE = 'NQF-0018' AND o.OBSERVATION_CODE = '85354-9')
      OR (qm.MEASURE_CODE = 'NQF-0421' AND o.OBSERVATION_CODE = '39156-5'))
WHERE qm.MEASURE_CODE IN ('NQF-0059', 'NQF-0018', 'NQF-0421', 'NQF-0002')
GROUP BY p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.FACILITY, p.RISK_TIER,
         qm.MEASURE_ID, qm.MEASURE_CODE, qm.MEASURE_NAME
HAVING (qm.MEASURE_CODE = 'NQF-0059' AND (MAX(o.VALUE_NUMERIC) >= 8.0 OR MAX(o.VALUE_NUMERIC) IS NULL))
    OR (qm.MEASURE_CODE = 'NQF-0018' AND (MAX(o.VALUE_NUMERIC) >= 140 OR MAX(o.VALUE_NUMERIC) IS NULL))
    OR (qm.MEASURE_CODE = 'NQF-0421' AND MAX(o.OBSERVATION_ID) IS NULL)
    OR (qm.MEASURE_CODE = 'NQF-0002' AND DATEDIFF(DAY, MAX(o.EFFECTIVE_DATE), CURRENT_DATE()) > 7);

------------------------------------------------------------
-- FHIR_VALIDATION_RESULTS (1-min lag)
-- Validates missing refs, invalid codes, bad dates
------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE FHIR_VALIDATION_RESULTS
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    e.ENCOUNTER_ID,
    e.PATIENT_ID,
    e.FHIR_RESOURCE_TYPE,
    e.FHIR_REFERENCE,
    e.ADMISSION_DATE,
    e.DISCHARGE_DATE,
    e.DIAGNOSIS_CODE,
    CASE
        WHEN p.PATIENT_ID IS NULL THEN 'MISSING_REFERENCE'
        WHEN e.DIAGNOSIS_CODE = 'INVALID_CODE' THEN 'INVALID_CODE'
        WHEN e.ADMISSION_DATE > e.DISCHARGE_DATE THEN 'INVALID_DATE_SEQUENCE'
        ELSE 'VALID'
    END AS VALIDATION_STATUS,
    CASE
        WHEN p.PATIENT_ID IS NULL THEN 'Patient reference ' || e.FHIR_REFERENCE || ' not found'
        WHEN e.DIAGNOSIS_CODE = 'INVALID_CODE' THEN 'Diagnosis code not in ICD-10 value set'
        WHEN e.ADMISSION_DATE > e.DISCHARGE_DATE THEN 'Admission date after discharge date'
        ELSE NULL
    END AS VALIDATION_MESSAGE,
    CASE
        WHEN p.PATIENT_ID IS NULL THEN 'Error'
        WHEN e.DIAGNOSIS_CODE = 'INVALID_CODE' THEN 'Error'
        WHEN e.ADMISSION_DATE > e.DISCHARGE_DATE THEN 'Warning'
        ELSE 'Pass'
    END AS SEVERITY,
    CURRENT_TIMESTAMP() AS VALIDATED_AT
FROM RAW.ENCOUNTERS e
LEFT JOIN RAW.PATIENTS p ON p.PATIENT_ID = e.PATIENT_ID;
