-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT facility.ID AS ENTITY_ID, facility.NAME AS ENTITY_NAME,
       facility.REGION, facility.CATEGORY, facility.INTEGRATION_TIER, facility.STATUS,
       facility.EXPECTED_BUNDLES_90D,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.BUNDLES_RECEIVED) AS BUNDLES_RECEIVED,
       SUM(observation.BUNDLES_ACCEPTED) AS BUNDLES_ACCEPTED,
       SUM(observation.ISSUE_COUNT) AS ISSUE_COUNT,
       SUM(observation.INCIDENT_COUNT) AS INCIDENT_COUNT,
       SUM(observation.TICKETS_OPENED) AS TICKET_COUNT,
       SUM(observation.CHECKS_DUE) AS CHECKS_DUE,
       SUM(observation.CHECKS_COMPLETED) AS CHECKS_COMPLETED,
       100.0 * SUM(observation.BUNDLES_ACCEPTED) / NULLIF(facility.EXPECTED_BUNDLES_90D, 0) AS COMPLETENESS_PCT,
       100.0 * (SUM(observation.BUNDLES_RECEIVED) - SUM(observation.BUNDLES_ACCEPTED)) / NULLIF(SUM(observation.BUNDLES_RECEIVED), 0) AS REJECTION_PCT,
       100.0 * SUM(observation.INCIDENT_COUNT) / NULLIF(SUM(observation.ISSUE_COUNT), 0) AS ESCALATION_PCT,
       100.0 * SUM(observation.CHECKS_COMPLETED) / NULLIF(SUM(observation.CHECKS_DUE), 0) AS CHECK_COMPLIANCE_PCT,
       AVG(observation.UNMAPPED_CODE_PCT) AS AVG_UNMAPPED_CODE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.FEED_DAILY observation
JOIN RAW.FACILITIES facility ON facility.ID = observation.ENTITY_ID
GROUP BY facility.ID, facility.NAME, facility.REGION, facility.CATEGORY, facility.INTEGRATION_TIER, facility.STATUS, facility.EXPECTED_BUNDLES_90D;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(BUNDLES_RECEIVED) AS BUNDLES_RECEIVED, SUM(BUNDLES_ACCEPTED) AS BUNDLES_ACCEPTED,
       SUM(ISSUE_COUNT) AS ISSUE_COUNT, SUM(INCIDENT_COUNT) AS INCIDENT_COUNT,
       100.0 * SUM(INCIDENT_COUNT) / NULLIF(SUM(ISSUE_COUNT), 0) AS ESCALATION_PCT
FROM RAW.FEED_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.ISSUE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ISSUE_TYPE, SUM(ISSUE_COUNT) AS ISSUE_COUNT,
       SUM(INCIDENT_COUNT) AS INCIDENT_COUNT,
       SUM(TICKETS_OPENED) AS TICKET_COUNT,
       COUNT(DISTINCT ENTITY_ID) AS FACILITIES_AFFECTED,
       100.0 * SUM(INCIDENT_COUNT) / NULLIF(SUM(ISSUE_COUNT), 0) AS ESCALATION_PCT
FROM RAW.FEED_DAILY
WHERE ISSUE_COUNT > 0
GROUP BY ISSUE_TYPE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(ISSUE_COUNT) AS ISSUES, SUM(INCIDENT_COUNT) AS INCIDENTS,
         SUM(TICKETS_OPENED) AS TICKETS, SUM(BUNDLES_RECEIVED) AS RECEIVED, SUM(BUNDLES_ACCEPTED) AS ACCEPTED,
         SUM(CHECKS_DUE) AS CHECKS_DUE, SUM(CHECKS_COMPLETED) AS CHECKS_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.FEED_DAILY
), network AS (SELECT COUNT(*) AS FACILITY_COUNT, SUM(EXPECTED_BUNDLES_90D) AS TARGET FROM RAW.FACILITIES),
profiles AS (
  SELECT 100.0 * SUM(LEAST(CONFORMANT_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.PROFILE_CONFORMANCE
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Feed Completeness' AS TITLE,
         100.0 * ACCEPTED / NULLIF(TARGET, 0) AS VALUE_NUM, '%' AS UNIT FROM observations CROSS JOIN network
  UNION ALL SELECT 2, 'Bundles Accepted', ACCEPTED, '' FROM observations
  UNION ALL SELECT 3, 'Bundle Rejection Rate', 100.0 * (RECEIVED - ACCEPTED) / NULLIF(RECEIVED, 0), '%' FROM observations
  UNION ALL SELECT 4, 'Issue Escalation Rate', 100.0 * INCIDENTS / NULLIF(ISSUES, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Data Quality Issues', ISSUES, '' FROM observations
  UNION ALL SELECT 6, 'Interface Incidents', INCIDENTS, '' FROM observations
  UNION ALL SELECT 7, 'Tickets Opened', TICKETS, '' FROM observations
  UNION ALL SELECT 8, 'Conformance Check Compliance', 100.0 * CHECKS_COMPLETED / NULLIF(CHECKS_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Facilities Connected', FACILITY_COUNT, '' FROM network
  UNION ALL SELECT 10, 'Profile Conformance', COVERAGE_PCT, '%' FROM profiles
  UNION ALL SELECT 11, 'Profile Reviews Pending', PENDING, '' FROM profiles
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.ISSUE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
