-- Healthcare Data Integration: Cortex Search
USE DATABASE HEALTHCARE_INTEGRATION;
USE SCHEMA SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE CARE_PATHWAY_SEARCH
    ON CONTENT
    ATTRIBUTES CATEGORY, TITLE
    WAREHOUSE = CORTEX
    TARGET_LAG = '1 hour'
AS (
    SELECT
        DOC_ID,
        TITLE,
        CATEGORY,
        CONTENT,
        LAST_UPDATED,
        VERSION,
        APPROVED_BY
    FROM RAW.CARE_PATHWAY_DOCS
);
