-- Interface incident risk scoring and accepted-bundle forecast over the synthetic snapshot.
-- Predicts P(interface incident in the next 7 days) per facility
-- and reports out-of-time holdout metrics; nothing is seeded as a prediction.
-- These are operational integration scores, not clinical predictions.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.INCIDENT_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, s.CATEGORY, s.INTEGRATION_TIER, s.YEARS_CONNECTED,
       r.UNMAPPED_CODE_PCT, r.FEED_LATENCY_HRS,
       AVG(r.UNMAPPED_CODE_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS UNMAPPED_CODE_7D,
       SUM(r.INCIDENT_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS INCIDENTS_30D,
       IFF(SUM(r.INCIDENT_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'INCIDENT', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.FEED_DAILY r JOIN RAW.FACILITIES s ON s.ID = r.ENTITY_ID
-- Regional network outages are not facility-driven, so they are excluded from training.
WHERE r.ISSUE_TYPE <> 'Regional network outage';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.INCIDENT_TRAIN AS
SELECT CATEGORY, INTEGRATION_TIER, YEARS_CONNECTED, UNMAPPED_CODE_PCT, FEED_LATENCY_HRS, UNMAPPED_CODE_7D, INCIDENTS_30D, LABEL
FROM ML.INCIDENT_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.INCIDENT_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, INTEGRATION_TIER, YEARS_CONNECTED, UNMAPPED_CODE_PCT, FEED_LATENCY_HRS, UNMAPPED_CODE_7D, INCIDENTS_30D, LABEL
FROM ML.INCIDENT_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.INCIDENT_RISK_MODEL(
  INPUT_DATA => TABLE(ML.INCIDENT_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.INCIDENT_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.INCIDENT_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'INTEGRATION_TIER', INTEGRATION_TIER, 'YEARS_CONNECTED', YEARS_CONNECTED,
           'UNMAPPED_CODE_PCT', UNMAPPED_CODE_PCT, 'FEED_LATENCY_HRS', FEED_LATENCY_HRS,
           'UNMAPPED_CODE_7D', UNMAPPED_CODE_7D, 'INCIDENTS_30D', INCIDENTS_30D)):probability:INCIDENT::FLOAT AS P
  FROM ML.INCIDENT_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'INCIDENT', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'INCIDENT', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'INCIDENT', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'INCIDENT', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per facility (label unknown, so excluded from features).
CREATE TABLE ML.INCIDENT_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.INCIDENT_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.INCIDENT_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'INTEGRATION_TIER', INTEGRATION_TIER, 'YEARS_CONNECTED', YEARS_CONNECTED,
           'UNMAPPED_CODE_PCT', UNMAPPED_CODE_PCT, 'FEED_LATENCY_HRS', FEED_LATENCY_HRS,
           'UNMAPPED_CODE_7D', UNMAPPED_CODE_7D, 'INCIDENTS_30D', INCIDENTS_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:INCIDENT::FLOAT, 4) AS INCIDENT_PROB_7D,
       CASE WHEN P:probability:INCIDENT::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:INCIDENT::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Network-wide accepted-bundle forecast (14 days) from the daily series, for capacity planning.
CREATE VIEW ML.DAILY_ACCEPTED AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(BUNDLES_ACCEPTED)::FLOAT AS BUNDLES_ACCEPTED
FROM RAW.FEED_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.BUNDLE_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ACCEPTED),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'BUNDLES_ACCEPTED'
);

CREATE TABLE ML.BUNDLE_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS BUNDLES_ACCEPTED,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.BUNDLE_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
