-- Healthcare Data Integration: ML Forecasting
USE DATABASE HEALTHCARE_INTEGRATION;
USE SCHEMA ML;

-- View: daily admissions by facility for forecasting
CREATE OR REPLACE VIEW ADMISSION_FORECAST_INPUT AS
SELECT
    FACILITY,
    ADMISSION_DATE AS DS,
    COUNT(*) AS ADMISSION_COUNT
FROM RAW.ENCOUNTERS
WHERE ADMISSION_DATE >= DATEADD(YEAR, -1, CURRENT_DATE())
    AND ADMISSION_DATE < CURRENT_DATE()
    AND STATUS = 'finished'
GROUP BY FACILITY, ADMISSION_DATE
ORDER BY FACILITY, DS;

-- Forecast model: admissions by facility (30-day horizon)
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ADMISSION_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ADMISSION_FORECAST_INPUT'),
    SERIES_COLNAME => 'FACILITY',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'ADMISSION_COUNT'
);

-- Generate 30-day forecast
CREATE OR REPLACE TABLE ADMISSION_FORECAST_RESULTS AS
CALL ADMISSION_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 30);
